<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>true</IsPackable>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <Description>High-performance serialization and deserialization of CBOR (Concise Binary Object Representation) data format from/to .NET objects and other types.</Description>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="System.Formats.Cbor" />
    </ItemGroup>

    <ItemGroup>
        <None Include="../../README.nuget.md" Pack="true" PackagePath="README.md" />
    </ItemGroup>

</Project>
